language: c
sudo: false
compiler:
 - gcc-7
 - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - clang
      - libsndfile-dev
      - libjack-jackd2-dev
      - jackd2
before_install:
 - "travis_retry curl -L
    https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    > /tmp/ninja-linux.zip"
 - unzip -d ~/.local/bin /tmp/ninja-linux.zip
 - pyenv shell 3.6
 - pip install meson
install:
 - meson build
 - ninja -C build
 - bash stoat_check.sh
script:
 - jackd -r -d dummy -r 44100 &
 - until jack_lsp; do sleep 0.01; done  # Wait for jackd
 - RAGE_ELEMENTS_PATH='.' ninja -C build test
 - kill %1
notifications:
  email: false
  irc:
    channels:
     - "chat.freenode.net#concertdaw"
    on_success: change
    on_failure: change
    template:
     - "%{repository_name}/%{branch} %{result}: %{build_url}"
