language: c
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - libsndfile-dev
      - libjack-jackd2-dev
      - jackd2
before_install:
 - "travis_retry curl -L
    https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    > /tmp/ninja-linux.zip"
 - unzip -d ~/.local/bin /tmp/ninja-linux.zip
 - pyenv shell 3.5
 - pip install meson
 - CC=gcc-5 meson build
install:
 - ninja -C build
script:
 - jackd -r -d dummy -r 44100 &
 - ninja -C build test
 - kill %1
